import org.gradle.api.tasks.testing.logging.TestLogEvent

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
repositories {
    jcenter()
    mavenCentral()
}

plugins {
    application
    kotlin("jvm") version "1.3.10"
}

dependencies {
    compile(kotlin("stdlib", "1.3.10"))
    compile(kotlin("reflect", "1.3.10"))
    testCompile(kotlin("test-common", "1.3.10"))
    testCompile(kotlin("test-annotations-common", "1.3.10"))
    testCompile(kotlin("test-junit", "1.3.10"))
    testCompile("com.willowtreeapps.assertk:assertk-jvm:0.12")
}
